### PR TITLE
Redid how Subfolders are handled

### PR DESCRIPTION
**Pull request by TheCandianVendingMachine**
I found that the official way to do subfolders was a bit clunky, so I made these changes instead.

The HTML file for the sub-page is modified directly via a regex in order to get the proper root folder from the subdirectory. Nothing is copied to the subdirectories as for they use the base theme file

What this changes: Now in the `md` files you can put as a link: `[subfolder link](sub1/sub2/file.html)` instead of `[subfolder link](file_sub1_sub2.html)`. In my opinion, this streamlines the process and allows for quick changes without having to find the new directory path. This also reduces bloat of the page as for the theme isn't being copied for each subdirectory.

### CODE REVIEW

**Comment by LittleCodingFox** [comment]
The problem with doing this is that it breaks navigation as soon as you go inside a directory. While you could solve this through a web server, you can't do this locally. Imagine you're at the root directory, then click a link "Subdirectory/some page.html". Suddenly the other links will no longer work, since you can't be sure where the root directory is.

Also, theme folders shouldn't default to having a "vendor" folder, so that bit of code is also troublesome.

The big problem is that navigation can't easily be fixed, which is why I settled for the way it is now. You'd have to go through all links after generating the markdown, using some sort of regex, and replace them with the proper path, in order to make this work properly with actual subdirectories.

**Comment by TheCandianVendingMachine** [comment]
For the first issue: Do you mean that in the users `.md` files you can't be sure that the user is being careful and respecting the folder structure, or do you mean that you can't have the Navigation Bar properly redirect you to the needed directories once you go past the root?

For the "vendor" folder issue, I am sure that there can be a way to automate that. As for I couldn't see any GUI way to change the theme folder, I kept that code ugly like that. I was aware of the issue and forgot to mention it.

**Comment by LittleCodingFox** [comment]
For the first: Both, actually. I guess an easy way to solve this would be to automatically parse links with no protocol or extension and search for a page with that same "baseName" and use that path based on the current directory of the page you're in.

Regarding the second issue, I already had code to copy the theme resources to the subdirectories, but we can probably add a keyword for the root directory so instead of writing '<script src="vendor/stuff"' it becomes '<script src="{ROOT_PATH}/vendor/stuff"' and the Core will just adjust the paths properly based on how deep we are directory-wise.

**Comment by TheCandianVendingMachine** [comment]
I think the idea for the `vendor` folder is good. If that doesn't turn out well you can probably just copy over the folder at the cost of the size.

I will try and implement the Navigation bar fix as well; I think that would be the best way to solve the problem.

**Comment by LittleCodingFox** [comment]
Thanks, I should have some news myself soon. Working on this right now (tho will have to leave soon).

**Comment by TheCandianVendingMachine** [comment]
With that commit the navigation bar issue is fixed. A very easy fix since we already were storing the recursive path. Now it navigates to the root folder, and then goes to whatever directory is wanted.

Only real issues are if the user misinterprets what they are supposed to do. If they mess up forget their path, we can't handle that without some serious checks that introduce issues with folder design. What I interpreted as your proposed solution would make it so the user can only have 1 file with a certain name, and that is not that great if a user wants multiple index files for each sub-directory.

**Comment by TheCandianVendingMachine** [comment]
Can you give me a test-case for that issue? I don't really understand how URL's are path dependent

**Comment by LittleCodingFox** [comment]
```
                 outNavigation.Add(new KeyValuePair<string, string>(pieces[0].Replace("\n", "").Replace("\r", "").Trim(),
                    recursivePath + pieces[1].Replace("\n", "").Replace("\r", "").Trim()));
```

If the navigation URL is something like "http://www.google.com" and your path is currently "Subdirectory", you'll have "Subdirectory\\http://www.google.com".

**Comment by TheCandianVendingMachine** [comment]
Sorry about all the things I forgot about. I have been working this for about 4 hours now, and it is 7:00AM.

**Comment by LittleCodingFox** [comment]
Hey, don't you worry about that. I'm thankful you're putting the effort to improve this. I'm working on this right now either way, so if you want to have a rest feel free. I'll let you know when I get progress on this.

**Comment by LittleCodingFox** [comment]
Just released an update that should solve all the subdirectory problems. Please let me know if you'd like any changes to it!

**Comment by TheCandianVendingMachine** [comment]
I think that the new solution is good. Closing this :+1:

**Pull request closed without merging**
